[project]
name = "infotheory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "network>=0.1",
    "numpy>=2.2.6",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "notebook>=7.4.2",
]
